version: "3.9"
services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/data/db

  user-service:
    build: .
    ports:
      - "3000:3000"
    environment:
      POSTGRES_HOST: postgres
    depends_on:
      - postgres
    volumes:
      - ./src:/usr/src/app/src

volumes:
  postgres-data: {}
