version: "3.9"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: ecommdb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/data/db


  user-service:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    volumes:
      - .:/usr/src/app

volumes:
  postgres-data: {}
